small typo
NikolayS/postgrest-google-translate pull request #13
Opened 2017-04-06 16:54 UTC by deemytch

2017-04-14 17:54 UTC, NikolayS commented on README.md
> +2. `plsh` – PostgreSQL contrib module, it is NOT included to standard contribs package. To install it on Ubuntu/Debian run: `apt-get install postgresql-X.X-plsh` (where X.X could be 9.5, depending on
2 уже было, тут должно быть 3

2017-04-14 17:55 UTC, NikolayS commented on README.md
> +3. Ruby for easy installer
Это следует обсудить — далеко не на всех машинах есть руби нужной версии или даже руби вообще... Действительно ли большая польза от добавления такого требования?

2017-04-14 19:56 UTC, NikolayS requested changes
1) я не уверен, что мы сможем воспользоваться ruby-скриптом — не везде есть ruby. Поэтому непонятно, как лучше быть с конфигурированием (стоит обсудить дополнительно).

2) Сейчас реализовано так, что для каждого API свой метод. Хотелось бы иметь «обёрточные» методы, которые абстрагируются от конкретного API, насколько это возможно — и иметь возможность  переключать API  конфигурацией (ещё один параметр, оперделяющий, какой сейчас API использовать). При условии сохранения api_engine в cache, это может быть очень удобно в том числе и для сравнения качества работы. Непонятно пока только, что у Promt с переводом пачек (массивов фраз) — эта возможность очень полезна, чтобы не делать много HTTP requests.

3) Ещё некоторые мелкие замечания см. в отдельных комментариях.

2017-04-14 19:56 UTC, NikolayS commented on README.md
> +psql -c "alter database DBNAME set translation_proxy.google_begin_at = '2000-01-01';"
Сейчас получается, что эти `begin_at` & `end_at` применяются только к Google API, хотя по идее могли бы применяться ко всем. 
Эти штуки нужны были, чтобы контролировать, когда мы используем  API, а когда полагаемся только на кэш.

2017-04-14 19:56 UTC, NikolayS commented on README.md
> +select * from translation_proxy.google_translate('en', 'ru', array['ok computer', 'show me more','hello world!']);
а для promt пачка фраз будет работать?

2017-04-14 19:56 UTC, NikolayS commented on install_api.sql
> +      where  username = 'apiuser'
тут всё же `usename`:

```
[local]:5432 nikolay@test=# \d pg_catalog.pg_user
     View "pg_catalog.pg_user"
    Column    |  Type   | Modifiers
--------------+---------+-----------
 usename      | name    |
 usesysid     | oid     |
 usecreatedb  | boolean |
 usesuper     | boolean |
 userepl      | boolean |
 usebypassrls | boolean |
 passwd       | text    |
 valuntil     | abstime |
 useconfig    | text[]  |
```

2017-04-14 19:56 UTC, NikolayS commented on install_google_core.sql
> +                    insert into translation_proxy.cache(source, target, q, result, api_engine)
у Promt есть ещё возможность использовать разные профили, также бывают разные версии API --
наверное, стоит тут добавить ещё один "слой" к `api_engine` (возможно, `api_version`)

это можно и отдельно, не в этом PR

2017-04-14 19:56 UTC, NikolayS commented on install_promt_core.sql
> +CREATE OR REPLACE FUNCTION translation_proxy._promt_translate_curl(text, text, char(2), char(2), text, text DEFAULT '') RETURNS text AS $$
вот тут последний параметр — его хорошо бы при сохранении в cache учитывать

2017-04-14 19:56 UTC, NikolayS commented on setup-example.yml
> +  :server_url: https://pts.promt.com/pts/
так будет двойной слэш образовываться

2017-04-17 05:29 UTC, deemytch commented on README.md
> +3. Ruby for easy installer
Если у человека нет ruby, можно всё запустить и ручками. Но неудобно...

2017-04-26 21:44 UTC, NikolayS approved these changes

2017-04-26 21:54 UTC, NikolayS requested changes

2017-04-26 21:54 UTC, NikolayS commented on uninstall_api.sql
> +revoke execute on function v1.promt_translate(char, char, text) from apiuser;
ещё пропустили момент -- в uninstall-скрипте везде схема `v2`.

Вообще, на v2 было необязательно переходить, т.к. пока нигде не нужно держать старую версию одновременно с новой.

Но раз перешли, то uninstall должен соответствовать (прошу проверить, что install & uninstall срабатывают по кругу).

2017-04-26 21:54 UTC, merged